/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/benchmark/': RouteRecordInfo<
      '/benchmark/',
      '/benchmark',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/benchmark/basic-table': RouteRecordInfo<
      '/benchmark/basic-table',
      '/benchmark/basic-table',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/benchmark/primevue-table': RouteRecordInfo<
      '/benchmark/primevue-table',
      '/benchmark/primevue-table',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/benchmark/tanstack-table': RouteRecordInfo<
      '/benchmark/tanstack-table',
      '/benchmark/tanstack-table',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home-page': RouteRecordInfo<
      '/home-page',
      '/home-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/species/': RouteRecordInfo<
      '/species/',
      '/species',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/species/[id]': RouteRecordInfo<
      '/species/[id]',
      '/species/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/about.vue': {
      routes:
        | '/about'
      views:
        | never
    }
    'src/pages/benchmark/index.vue': {
      routes:
        | '/benchmark/'
      views:
        | never
    }
    'src/pages/benchmark/basic-table.vue': {
      routes:
        | '/benchmark/basic-table'
      views:
        | never
    }
    'src/pages/benchmark/primevue-table.vue': {
      routes:
        | '/benchmark/primevue-table'
      views:
        | never
    }
    'src/pages/benchmark/tanstack-table.vue': {
      routes:
        | '/benchmark/tanstack-table'
      views:
        | never
    }
    'src/pages/home-page.vue': {
      routes:
        | '/home-page'
      views:
        | never
    }
    'src/pages/species/index.vue': {
      routes:
        | '/species/'
      views:
        | never
    }
    'src/pages/species/[id].vue': {
      routes:
        | '/species/[id]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
